version: '3.1'

services:
  oneframe:
    image: paidyinc/one-frame
    hostname: oneframe
    container_name: one-frame
    ports:
      - 8081:8080
    networks:
      - default

  memcached:
    image: memcached:1.6.12-bullseye
    hostname: memcached
    container_name: memcached
    ports:
      - 11211:11211
    networks:
      - default

#  app:
#    image: forex:1.0.1
#    container_name: app
#    depends_on:
#      - "oneframe"
#      - "memcached"
#    ports:
#      - 8080:8080
#    links:
#      - "memcached:memcached"
#      - "oneframe:oneframe"
#    networks:
#      - default

networks:
  default:
    driver: bridge