version: '3.1'

services:
  oneframe:
    image: paidyinc/one-frame
    container_name: one-frame
    ports:
      - 8081:8080

#  db:
#    image: mysql:5.7
#    container_name: db
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - 3306:3306
#    volumes:
#      - "./../sql/gladiator/ddl.sql:/docker-entrypoint-initdb.d/gladiator.sql"
#      - "./../sql/trm/mysql/ddl/ddl.sql:/docker-entrypoint-initdb.d/trm.sql"
#      - "./../sql/tm/mysql/ddl/ddl.sql:/docker-entrypoint-initdb.d/tm.sql"